import { Link, useParams } from 'react-router-dom'
import { experiences } from '../data/experiences'

export default function ExperiencePage() {
  const { slug } = useParams()
  const experience = experiences.find(item => item.slug === slug)
  if (!experience) return <div className="pt-24"><h1 className="text-2xl font-semibold">Experience not found.</h1><Link className="mt-4 inline-block text-sm underline" to="/work">Back to work experience</Link></div>
  const timeline = experience.timeline ?? [{ role: experience.role, dates: experience.dates, bullets: experience.bullets }]
  return <article className="pt-16 sm:pt-24"><Link to="/work" className="text-sm text-neutral-500">← Back to work experience</Link><div className="mt-10 flex flex-col gap-2 sm:flex-row sm:items-baseline sm:justify-between"><h1 className="text-3xl font-semibold tracking-tight">{experience.company}</h1><time className="text-sm text-neutral-500">{experience.dates}</time></div><p className="mt-2 text-sm text-neutral-500">{experience.role} · {experience.location}</p><p className="mt-8 max-w-xl border-l-2 border-neutral-300 pl-4 text-sm leading-7 text-neutral-600 dark:border-neutral-700 dark:text-neutral-300">{experience.highlight}</p><div className="mt-10 max-w-2xl border-y border-neutral-200 py-5 dark:border-neutral-800"><h2 className="text-xs font-semibold uppercase tracking-[0.16em] text-neutral-500">Tools and technologies</h2><div className="mt-4 flex flex-wrap gap-2">{experience.stack.split(', ').map(tool => <span key={tool} className="border border-neutral-300 bg-neutral-100 px-3 py-1.5 text-sm font-medium text-neutral-800 dark:border-neutral-700 dark:bg-neutral-900 dark:text-neutral-100">{tool}</span>)}</div>{experience.aiTools && <div className="mt-5"><h3 className="text-xs font-semibold uppercase tracking-[0.16em] text-neutral-500">AI tools</h3><div className="mt-3 flex flex-wrap gap-2">{experience.aiTools.map(tool => <span key={tool} className="border border-neutral-950 bg-neutral-950 px-3 py-1.5 text-sm font-medium text-white dark:border-white dark:bg-white dark:text-neutral-950">{tool}</span>)}</div></div>}</div><div className="mt-12 max-w-2xl"><h2 className="text-xs font-semibold uppercase tracking-[0.16em] text-neutral-500">Timeline</h2><div className="mt-6 space-y-10">{timeline.map(item => <section key={`${item.role}-${item.dates}`}><div className="flex flex-col gap-1 sm:flex-row sm:items-baseline sm:justify-between"><h3 className="font-medium">{item.role}</h3><time className="text-xs text-neutral-500">{item.dates}</time></div><ul className="mt-4 list-inside list-disc space-y-4 text-sm leading-7 text-neutral-700 dark:text-neutral-300">{item.bullets.map(bullet => <li key={bullet}>{bullet}</li>)}</ul></section>)}</div></div></article>
}
